language: objective-c
notifications:
  email: false
osx_image: xcode7.3
script:
  xcodebuild -workspace CollectionVariable.xcworkspace -scheme CollectionVariable -destination "OS=9.3,name=iPhone 6S Plus" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" build | xcpretty -c
  xcodebuild -workspace CollectionVariable.xcworkspace -scheme CollectionVariable -destination "OS=9.3,name=iPhone 6S Plus" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" test | xcpretty -c
before_script:
- carthage checkout --no-use-binaries
